apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svt
spec:
  selector:
    app: {{ .Release.Name }}-svt  
  ports:
    - protocol: TCP
      port: 8080  
      targetPort: 8080 
  type: ClusterIP  
