apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svt
spec:
  selector:
    app: {{ .Release.Name }}-svt  
  ports:
    - protocol: TCP
      port: {{ .Values.svt.ports[0].servicePort }}  
      targetPort: {{ .Values.svt.ports[0].containerPort }}  
  type: ClusterIP  
