apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-svt-pv
spec:
  capacity:
    storage: 1Gi  # Size of the volume
  accessModes:
    - ReadWriteOnce  # Define the access mode (should match the PVC access mode)
  persistentVolumeReclaimPolicy: Retain  # Define the reclaim policy (Retain, Delete, etc.)
  storageClassName: standard  # Match this with your PVC's storage class
  hostPath:
    path: "/mnt/data/{{ .Release.Name }}-svt"  # Local path for storage (for Minikube or similar setups)
    type: DirectoryOrCreate  # Automatically create the directory if it doesn't exist
  volumeMode: Filesystem  # Specify the volume mode (this was missing previously)
