apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-svt
spec:
  replicas: {{ .Values.svt.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-svt
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-svt
    spec:
      containers:
        - name: svt
          image: "jayaprakash247/svt:latest"
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "{{ .Values.svt.resources.requests.memory }}"
              cpu: "{{ .Values.svt.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.svt.resources.limits.memory }}"
              cpu: "{{ .Values.svt.resources.limits.cpu }}"
          volumeMounts:
            - name: svt-data
              mountPath: /data
            - name: svt-config
              mountPath: /etc/svt/config
              readOnly: true
      volumes:
        - name: svt-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-svt-pvc
        - name: svt-config
          configMap:
            name: {{ .Release.Name }}-svt-config

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-svt-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/mnt/data/{{ .Release.Name }}-svt"
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-svt-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeMode: Filesystem
