apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svtui
spec:
  selector:
    app: {{ .Release.Name }}-svtui  
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80  
  type: ClusterIP  
